### ISSUE TITLE
Please upgrade source-map to 0.7.2 to get speed improvements

### ISSUE THREAD

**Issue by andreicristianpetcu** [clean-css/clean-css#1012]
The latest source-map which is v0.7.2 got support for WebAssembly and it is 10 times faster than the old one. More info here:

https://github.com/mozilla/source-map/blob/master/CHANGELOG.md#072
http://fitzgeraldnick.com/2018/02/26/speed-without-wizardry.html
https://hacks.mozilla.org/2018/01/oxidizing-source-maps-with-rust-and-webassembly/
https://github.com/devtools-html/debugger.html/issues/5598

Please update so you would get 10 times speed improvements for your library in Firefox, 9 times in Safari and 5 times in Chrome.

**Comment by jakubpawlowicz** [comment]
Sure, we can do it in 4.2.0.

**Comment by realityking** [comment]
Note `source-map` 0.7 requires Node.js 8

**Comment by jakubpawlowicz** [comment]
I planned to drop Node.js 4 in clean-css 5 but there may be a point in dropping Node.js 6 too when Node.js 10 is out so we can use the source-map 0.7.

**Comment by jakubpawlowicz** [comment]
Won't fix. I've tried to migrate to source-map 0.7 multiple times and their promise-based API didn't work for me. Closing it as clean-css is going into [maintenance mode](https://github.com/clean-css/clean-css/discussions/1209).
