### ISSUE TITLE
text-transform properties do not merge

### ISSUE THREAD

**Issue by lumberman** [clean-css/clean-css#1020]
Hello,
Thanks for this amazing work.

I believe there is an issue with merging multiple text-transform properties.

**Source:**
.test {
  text-transform: uppercase;
  text-transform: capitalize
}

**Result:**
.test {
  text-transform: uppercase;
  text-transform: capitalize
}

**Expected:**
.test {
  text-transform: capitalize
}

Can you please help?

**Comment by jakubpawlowicz** [comment]
Won't fix as clean-css is going into [maintenance mode](https://github.com/clean-css/clean-css/discussions/1209).
