### ISSUE TITLE
Multiply letter-spacing properties will not merge

### ISSUE THREAD

**Issue by lumberman** [clean-css/clean-css#1024]
There is an issue with merging multiple letter-spacing properties.
Tested on a local install and confirmed on https://jakubpawlowicz.github.io/clean-css/

**Source:**
.test {
 letter-spacing: 3px;
  letter-spacing: 2px;
  letter-spacing: 3px;
  letter-spacing: 4px;
  letter-spacing: 6px;
  letter-spacing: 7px;
}

**Result:**
.test {
 letter-spacing: 3px;
  letter-spacing: 2px;
  letter-spacing: 3px;
  letter-spacing: 4px;
  letter-spacing: 6px;
  letter-spacing: 7px;
}

**Expected:**
.test {
 letter-spacing: 7px;
}

**Comment by jakubpawlowicz** [comment]
Won't fix as clean-css is going into [maintenance mode](https://github.com/clean-css/clean-css/discussions/1209).
