### ISSUE TITLE
Multiply word-spacing, text-indent, font-style properties will not merge

### ISSUE THREAD

**Issue by lumberman** [clean-css/clean-css#1025]
There is an issue with merging multiple word-spacing, text-indent and font-style properties.
Tested on a local install and confirmed on https://jakubpawlowicz.github.io/clean-css/

Source:
.test {
word-spacing: 3px;
word-spacing: 2px;
word-spacing: 3px;

text-indent: 4px;
text-indent: 6px;
text-indent: 7px;

font-style: normal;
font-style: inherit;
font-style: italic;
}

Result:
.test {
word-spacing: 3px;
word-spacing: 2px;
word-spacing: 3px;
text-indent: 4px;
text-indent: 6px;
text-indent: 7px;
font-style: normal;
font-style: inherit;
font-style: italic;
}

Expected:
.test {
word-spacing: 3px;
text-indent: 7px;
font-style: italic;
}

**Comment by jakubpawlowicz** [comment]
Won't fix as clean-css is going into [maintenance mode](https://github.com/clean-css/clean-css/discussions/1209).
