### ISSUE TITLE
@import path are relative to cwd rather than file path

### ISSUE THREAD

**Issue by alan-agius4** [clean-css/clean-css#1029]
### Precheck
 
* Do a quick search and make sure a bug has not yet been reported;
* do a quick check if the bug still exists in the latest patch version;
* finally, be nice and have fun!

### Environment

* clean-css version - 4.1.11:
* operating system: Mac OSX

### Configuration options

```js
var CleanCSS = require('clean-css');
new CleanCSS({level: 2})
```

### Input CSS

```css
@import "../../../node_modules/filepond/dist/filepond.css"
```

### Actual output CSS
Exception
```
Error: Ignoring local @import of "../../../node_modules/filepond/dist/filepond.css" as resource is missing.
```

### Expected output CSS
Embedded css

### More Details

The problem here is that the path is being taken relative to the `process.cwd` rather than the actual source file. I suggest that the path of the `import` that into consideration the input file path and not just the process.cwd()

**Comment by jakubpawlowicz** [comment]
Won't fix as clean-css is going into [maintenance mode](https://github.com/clean-css/clean-css/discussions/1209).

**Comment by binyamin** [comment]
@jakubpawlowicz Thanks for your work here, you built a great tool. According to the readme, CleanCSS _will_ receive occasional bug-fixes. Shouldn't this qualify? Currently, the `rebaseTo` option seems to do nothing.
