### ISSUE TITLE
Rebasing Relative URLs when working with CSS string and URL strings ONLY

### ISSUE THREAD

**Issue by tomgallagher** [clean-css/clean-css#1040]
So I have the source file url:

`var cssURL = "https://www.example.com/resources/dir4/dir3/dir2/dir1/screen.css";`

which contains the following CSS string:

`.badge-40 { background-image: url(images/sprites/badges-50-sprite.png); }, .badge-50 { background-image: url(/images/sprites/badges-50-sprite.png); }, .badge-60 { background-image: url(https://www.example.com/images/sprites/badges-60-sprite.png); }, .badge-70 { background-image: url("../images/sprites/badges-70-sprite.png"); }, .badge-80 { background-image: url('../../images/sprites/badges-80-sprite.png'); }, .badge-90 { background-image: url('../../../images/sprites/badges-90-sprite.png'); }`;`

Then I use the following code to create the absolute URL, making allowance for the variations of no quotes, single quotes and double quotes:

```
new CleanCSS({ 
        returnPromise: true, 
        level: {
            1: {
               transform: function (propertyName, propertyValue) {
                    var getBackgroundImageRegEx = /url(?:\(['"]?)(.*?)(?:['"]?\))/g;
                    if (propertyName == 'background-image' && propertyValue.startsWith('url(')) {
                        var source = getBackgroundImageRegEx.exec(propertyValue)[1];
                        switch (true) {
                                case source.startsWith('/'):
                                    return propertyValue;
                                case source.startsWith('http'):
                                   return propertyValue;
                                case source.startsWith('../../../'):
                                    var threeDirectoriesBackRelativeURL = cssURL.split('/').slice(0,-4).join('/');
                                    return `url(${threeDirectoriesBackRelativeURL}/${source.replace('../../../', '')})`;
                                case source.startsWith('../../'):
                                    var twoDirectoriesBackRelativeURL = cssURL.split('/').slice(0,-3).join('/');
                                    return `url(${twoDirectoriesBackRelativeURL}/${source.replace('../../', '')})`;
                                case source.startsWith('../'):
                                    var oneDirectoryBackRelativeURL = cssURL.split('/').slice(0,-2).join('/');
                                    return `url(${oneDirectoryBackRelativeURL}/${source.replace('../', '')})`;
                                default:
                                    var basicRelativeURL = cssURL.split('/').slice(0,-1).join('/');
                                    return `url(${basicRelativeURL}/${source})`;
                            }
                    }
                }
            }
        }
    })
    .minify(cssString)
    .then(output => { 
        console.log(output.styles);
    });
```

This returns the CSS adjusted as required:

`.badge-40{background-image:url(https://www.example.com/resources/dir4/dir3/dir2/dir1/images/sprites/badges-50-sprite.png)},.badge-50{background-image:url(/images/sprites/badges-50-sprite.png)},.badge-60{background-image:url(https://www.example.com/images/sprites/badges-60-sprite.png)},.badge-70{background-image:url(https://www.example.com/resources/dir4/dir3/dir2/images/sprites/badges-70-sprite.png)},.badge-80{background-image:url(https://www.example.com/resources/dir4/dir3/images/sprites/badges-80-sprite.png)},.badge-90{background-image:url(https://www.example.com/resources/dir4/images/sprites/badges-90-sprite.png)}`

which is what I'm after.

I had a couple of questions. 

If a relative URL requires more than three dot segments / directory steps backwards, so like this `../../../../`, then the `propertyValue` returns only three dot segments. Is this compliant with standards as I thought any length was legitimate?

Also, my code seems fragile to me. I'm not a fan of using regexes like this and I thought the auto-adjustment of relative URLs might be included in the package somewhere. I've tried rebaseTo but this includes my workspace URL in the output.

Any help would be much appreciated.

**Comment by jakubpawlowicz** [comment]
Won't fix as clean-css is going into [maintenance mode](https://github.com/clean-css/clean-css/discussions/1209).
