### ISSUE TITLE
Rebasing @import Relative URLs when working with CSS string and URL strings ONLY

### ISSUE THREAD

**Issue by tomgallagher** [clean-css/clean-css#1041]
So I have the source file url:

`var cssURL = "https://www.example.com/resources/dir4/dir3/dir2/dir1/screen.css";`

which contains the following CSS string:

`@import url('consumers-blessed2.css'); @import url('consumers-blessed1.css');`

How can I get the following output?

`@import url('https://www.example.com/resources/dir4/dir3/dir2/dir1/consumers-blessed2.css'); @import url('https://www.example.com/resources/dir4/dir3/dir2/dir1/consumers-blessed1.css');`

The transform function in Level 1 optimizations does not pick up the @import rule. 

Any help much appreciated.

**Comment by Hibrix-net** [comment]
#1100

**Comment by jakubpawlowicz** [comment]
Won't fix as clean-css is going into [maintenance mode](https://github.com/clean-css/clean-css/discussions/1209).
