### ISSUE TITLE
Modernize codebase

### ISSUE THREAD

**Issue by XhmikosR** [clean-css/clean-css#1095]
@jakubpawlowicz the first thing I hit in my branch is which Node.js 8 version we should use.

IMO we should use `>= 8.10.0` for object spread. But maybe we should just require 10.0.0.

**Comment by XhmikosR** [comment]
I'll take a stab at it in the following days. It will be a substantial amount of changes, so before I proceed let's discuss some of the rules so that we save time.

1. [curly](https://eslint.org/docs/rules/curly): IMHO curly braces should be used everywhere, but please check the available ESLint options and let me know which one you prefer
2. [object-curly-spacing](https://eslint.org/docs/rules/object-curly-spacing#enforce-consistent-spacing-inside-braces-object-curly-spacing)
3. [quote-props](https://eslint.org/docs/rules/quote-props#require-quotes-around-object-literal-property-names-quote-props)
4. [space-before-function-paren](https://eslint.org/docs/rules/space-before-function-paren#require-or-disallow-a-space-before-function-parenthesis-space-before-function-paren): I'll go with `never` since it seems to match the existent style

I have a WIP branch on my fork (https://github.com/jakubpawlowicz/clean-css/compare/master...XhmikosR:lint). I'll update it after you leave me some feedback, finalize it and make a PR, which we can discuss in detail later.

IMHO vows should be replaced with something else too, but I'll leave that for you to decide since it's mostly an internal thing :)

**Comment by jakubpawlowicz** [comment]
Hey @XhmikosR as we agreed via email please don't touch it yet. When time is right we will get back to modernizing the codebase. I don't want you to waste your limited time resources on this. But thanks for contributing some ideas here!

**Comment by jakubpawlowicz** [comment]
@johannchopin here are my comments based for #1199 

- `curly` - `all`
- `object-curly-spacing` - `always`
- `quote-props` - `as-needed` 
- `space-before-function-paren` - `never` to match the existing style

**Comment by jakubpawlowicz** [comment]
Eslint is now in, but closing the issue now as clean-css is going into [maintenance mode](https://github.com/clean-css/clean-css/discussions/1209).
