### ISSUE TITLE
How can i keep import path not parsed?

### ISSUE THREAD

**Issue by tyonly** [clean-css/clean-css#1114]
### Precheck
 
* Do a quick search and make sure a bug has not yet been reported;
* do a quick check if the bug still exists in the latest patch version;
* finally, be nice and have fun!

### Environment

* clean-css version - `npm ls clean-css`:
* node.js version - `node -v`:
* operating system:

### Configuration options

```js
var CleanCSS = require('clean-css');
new CleanCSS({inline:false
})
```

### Input CSS

```css
/* the shorter the better! */
@import "../cell-group/index.wxss";
```

### Actual output CSS

```css
@import url(../cell-group/index.wxss);
```

### Expected output CSS
```css
@import "../cell-group/index.wxss";
```
How can I get it ？

**Comment by janebt** [comment]
I meet the same question too

**Comment by suncxq** [comment]
mark

**Comment by yiqianglin** [comment]
mark，same question！！！

**Comment by yiqianglin** [comment]
> ### Precheck
> * Do a quick search and make sure a bug has not yet been reported;
> * do a quick check if the bug still exists in the latest patch version;
> * finally, be nice and have fun!
> 
> ### Environment
> * clean-css version - `npm ls clean-css`:
> * node.js version - `node -v`:
> * operating system:
> 
> ### Configuration options
> ```js
> var CleanCSS = require('clean-css');
> new CleanCSS({inline:false
> })
> ```
> 
> ### Input CSS
> ```css
> /* the shorter the better! */
> @import "../cell-group/index.wxss";
> ```
> 
> ### Actual output CSS
> ```css
> @import url(../cell-group/index.wxss);
> ```
> 
> ### Expected output CSS
> ```css
> @import "../cell-group/index.wxss";
> ```
> 
> How can I get it ？

is there any solution?

**Comment by jakubpawlowicz** [comment]
@yiqianglin and others - you are right, the shorter the better, so we should stick to the version without `url()`.

However the issue says "How can I keep path not parsed?" - does it mean you want a way to keep it always as is? E.g. if there's an import:

```css
@import url(reset.css);
``` 

should we keep it as is or make it shorter?

I'm trying to understand requirements here.

**Comment by jakubpawlowicz** [comment]
Won't fix as clean-css is going into [maintenance mode](https://github.com/clean-css/clean-css/discussions/1209).
