### ISSUE TITLE
Add coverage support?

### ISSUE THREAD

**Issue by XhmikosR** [clean-css/clean-css#1150]
@jakubpawlowicz how do you feel about add coverage support? If you agree, which service would you like to use? Codegov, coveralls, something else?

I can make a PR later.

**Comment by jakubpawlowicz** [comment]
I have no preference. What's better / faster / more widely used?

**Comment by XhmikosR** [comment]
I think coveralls might be more popular, but codegov seems good too. Your call :)

PS. this is the last step just so that you connect the repo to a service. I'll experiment with a couple different ways to get the coverage report and submit a PR.

**Comment by jakubpawlowicz** [comment]
Let me have a look then.

**Comment by jakubpawlowicz** [comment]
Won't fix as clean-css is going into [maintenance mode](https://github.com/clean-css/clean-css/discussions/1209).
