### ISSUE TITLE
optimization for nth-child & nth-of-type

### ISSUE THREAD

**Issue by da0ka** [clean-css/clean-css#1159]
nth-child(1) -> first-child
nth-of-type(1) -> first-of-type
nth-of-type(even) -> nth-of-type(2n)
nth-child(even) -> nth-child(2n)
nth-of-type(2n+1) -> nth-of-type(odd)
nth-child(2n+1) -> nth-child(odd)

**Comment by jakubpawlowicz** [comment]
I think all of them are equally well supported, if so, let's have it 👍

**Comment by jakubpawlowicz** [comment]
Due in 5.3 tomorrow.
