### ISSUE TITLE
WARNING: Skipping remote @import of "https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" as resource is not allowed.

### ISSUE THREAD

**Issue by yurj** [clean-css/clean-css#1190]
* clean-css version - clean-css@5.2.2
* node.js version - v16.13.0
* operating system: Linux

cleancss --format breakWith=lf --source-map --source-map-inline-sources --output css/theme.min.css css/theme.css

### Input CSS

// Fonts
@import url("https://fonts.googleapis.com/css?family=Oswald");

// Bootstrap Icons
@import url("https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css");

### Actual output CSS

empty

### Expected output CSS

with Oswal fonts and BS icons css

If I download the remote css and do a local @import 'fonts.css' it works

**Comment by Jaakkonen** [comment]
You need to enable remote inlining with `--inline remote` option. I recommend you to read the documentation at https://github.com/clean-css/clean-css-cli.
