### ISSUE TITLE
Clean CSS doesn't remove invalid CSS properties

### ISSUE THREAD

**Issue by erropix** [clean-css/clean-css#1191]
### Environment

* clean-css version - `5.2.2`:
* node.js version - `v16.13.0`:
* operating system: `Windows 10`

### Configuration options

```js
var CleanCSS = require('clean-css');
new CleanCSS({
  level: 2
})
```

### Input CSS

```css
a { font-weight: bold; invalid-property: 20px; }
```

### Actual output CSS

```css
a{font-weight:700;invalid-property:20px}
```

### Expected output CSS

```css
a{font-weight:700}
```

Is there something I am missing in the config?

**Comment by jakubpawlowicz** [comment]
Hey @ERROPiX - we don't remove unused properties yet, however it would be pretty simple to add, see:

- list of valid CSS properties - https://developer.mozilla.org/en-US/docs/Web/CSS/Reference#index
- clean-css plugins - https://github.com/clean-css/clean-css#plugins
- level 1 plugin example - https://github.com/clean-css/clean-css/blob/master/lib/optimizer/level-1/property-optimizers/font-weight.js

If you'd like to submit a PR for it, then please remember to make such optimization optional, as not all properties are documented, so it may unintentionally break styling.

Let me know if you need any further help with it.

**Comment by ERROPiX** [comment]
@jakubpawlowicz thanks for the confirmation, however I tried using a plugin to empty the property value, like:

```js
var myPlugin = {
  level1: {
    property: function removeRepeatedBackgroundRepeat(_rule, property, _options) {
      // So `background-repeat:no-repeat no-repeat` becomes `background-repeat:no-repeat`
      if (property.name == 'invalid-property') {
        property.value = [];
        property.dirty = true;
      }
    }
  }
}

new CleanCSS({plugins: [myPlugin]})
```

But the output CSS contains the property with empty value:

```css
a{font-weight:700;invalid-property:}
```
To get rid of the property, I had to use `property.unsed = true;`

**Comment by jakubpawlowicz** [comment]
Cool, glad you found a way. Please feel free to update the docs if you find them lacking.

**Comment by jakubpawlowicz** [comment]
Won't fix as clean-css is going into [maintenance mode](https://github.com/clean-css/clean-css/discussions/1209).
