### ISSUE TITLE
Units stripped from zeros even when required for css math functions

### ISSUE THREAD

**Issue by kstrickland0612** [clean-css/clean-css#1192]
### Environment

* clean-css version - `clean-css@4.2.3`
* node.js version - `v14.15.5`
* operating system: macOS Big Sur v11.6

### Configuration options

```js
var CleanCSS = require('clean-css');
new CleanCSS({})
```

### Input CSS

```css
margin: 0 min(calc((1280px - 100vw) / 2), -0px)
```

### Actual output CSS

```css
margin: 0 min(calc((1280px - 100vw)/ 2),0)
```
The `0` that's the second argument to `min()` does not have units (px) so `min()` is unable to compute the result. This leads to an "invalid property value" warning and the desired style not being applied:

![6A628DC4-77D2-460F-AFBB-A7FF677F00B5_4_5005_c](https://user-images.githubusercontent.com/48263994/145275063-742bdfbb-07f9-4d92-8da3-cc401071388f.jpeg)

### Expected output CSS

```css
margin: 0 min((1280px - 100vw) / 2, 0px)
```

### Proposal

The minifier should not strip the units when they are being used in a [css math function](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Functions#math_functions) (ex: `min()`, `max()`, `calc()`, `clamp()`).
My current workaround is to disable the `zeroUnits` rule, but obviously that's not ideal since I only need to preserve the units used in css math functions.

**Comment by jakubpawlowicz** [comment]
Hey @kstrickland0612 - any chance you can update to clean-css 5.x as it's fixed there?

**Comment by kstrickland0612** [comment]
Thanks @jakubpawlowicz, good to know. 
We're using clean-css via https://github.com/kangax/html-minifier, so I'll check over there about making the dep update. Their latest version (4.0.0) has clean-css set at ^4.2.1.
