### ISSUE TITLE
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default

### ISSUE THREAD

**Issue by n8sabes** [clean-css/clean-css#1193]
`Clean-css` in a browser-based project fails to build after updating to latest `create-react-app`. (`react-scripts ^5.0.0` which uses webpack 5). This issue is also being discussed in the CRA project: [v5 used to include polyfills for node.js core modules by default](https://github.com/facebook/create-react-app/issues/11756).

**BUILD ERRORS**
``` shell
ERROR in PROJECT/node_modules/clean-css/lib/reader/rewrite-url.js 1:11-26
Module not found: Error: Can't resolve 'path' in 'PROJECT/node_modules/clean-css/lib/reader'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
	- install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "path": false }
```

**SPECIFIC POLYFILL ISSUES IN CLEAN-CSS**
```
Module not found: Error: Can't resolve 'os'
Module not found: Error: Can't resolve 'path'
Module not found: Error: Can't resolve 'fs'
Module not found: Error: Can't resolve 'https'
Module not found: Error: Can't resolve 'http'
```

**PACKAGES**
```
"react-scripts": "^5.0.0",
"clean-css": "^5.2.2",
```

Is this something that can be resolved in `clean-css`, or is forcing polyfills for webpack 5 the only path forward? Forcing polyfills becomes complicated with [CRACO](https://github.com/gsoft-inc/craco) and other toolchains such as `esBuild`/`swc`. [e.g.` "@craco/craco": "^6.4.3", "craco": "^0.0.3", "craco-esbuild": "^0.4.3", "craco-swc": "^0.2.0",`].

**Comment by jakubpawlowicz** [comment]
Hey @n8sabes - sorry, but I don't have an idea how to fix it.

**Comment by jakubpawlowicz** [comment]
Closing, but please reopen if it still needs discussion.
