### ISSUE TITLE
Allow to preserve an unknown properties

### ISSUE THREAD

**Issue by Xardion495** [clean-css/clean-css#1198]
### Precheck
 
If needed to control an "unknown" properties (in terms of vscode linter), clean-css doesn't provide any option to do it.
'skipProperties' option doesn't resolve this.
It's can be useful if dev want to control svg (implemented in html document directly) and it's child elems from css.

### Environment

* clean-css version - `npm ls clean-css`: 4.2.3
* node.js version - `node -v`: 16.13.1
* operating system: Win10 x64 (21H1, build 19044.1469)

**Comment by jakubpawlowicz** [comment]
Hey @Xardion495 - do you mean there should be a switch which lets clean-css treat any non-standard CSS properties as valid ones and simply keep them as they are? I believe it works in clean-css 5.x - can you at least give it a try at https://clean-css.github.io/ ?

**Comment by Xardion495** [comment]
> I believe it works in clean-css 5.x - can you at least give it a try at https://clean-css.github.io/ ?

Hi. Yeah, you are right, it works at https://clean-css.github.io
I using gulp with clean-css wrapper plugin which depends on old clean-css version.
So i used solution from here: https://github.com/clean-css/clean-css/pull/1173 and the problem is no more.
Thanks for responses.

**Comment by jakubpawlowicz** [comment]
Cool, no problem!
