### ISSUE TITLE
 clean-css :Unhandled 'error' event

### ISSUE THREAD

**Issue by snaveenpandi** [clean-css/clean-css#1203]
Docusaurus versioning  2.0.0alpha16 to 2.0.0beta15  is working fine at local,if i build i got error ,help to resolved this issue

![Screenshot from 2022-02-25 12-08-49](https://user-images.githubusercontent.com/49641942/155679583-29af324b-373f-4330-bffe-6e53ec4ec712.png)

**Comment by jakubpawlowicz** [comment]
Hi @snaveenpandi - I need to know what version of clean-css you are using.

Also you can disable at rules optimizing by passing `{level: {2: {removeUnusedAtRules: false}}}` to clean-css, see https://github.com/clean-css/clean-css#level-2-optimizations

**Comment by snaveenpandi** [comment]
clean-css version **5.1.5**

where can i changes this above mention step,could u please explain

**Comment by jakubpawlowicz** [comment]
Probably the newest one, 5.2.4, won't change a thing here.

It depends what you use to execute clean-css, I guess a build system, sth like webpack. How is docs.mirrorfly.com website built? This is out of scope of my expertise but I'll try to help.

**Comment by jakubpawlowicz** [comment]
Closing as I'd need more details to help with a fix. Please reopen if needed.
