### ISSUE TITLE
import statement gets broken

### ISSUE THREAD

**Issue by aguidrevitch** [clean-css/clean-css#1239]
Hi there,

@import urls gets broken if there is no space after url(), eg `@import url("some.css")print;` which is perfectly valid CSS as reported by https://jigsaw.w3.org/css-validator/#validate_by_input+with_options. 

### Environment

* clean-css version - `npm ls clean-css`: clean-css@5.3.1
* node.js version - `node -v`: v18.5.0
* operating system: macos catalina

### Configuration options

```js
var CleanCSS = require('clean-css');
new CleanCSS({})
```

### Input CSS

```css
@import url("some.css")print;
```

### Actual output CSS

```css
@import url('some.css)print');
```

### Expected output CSS

```css
@import url("some.css")print;
```

**Comment by jakubpawlowicz** [comment]
The fix is out in 5.3.2.
