### ISSUE TITLE
Reordering media blocks to assist in media merging

### ISSUE THREAD

**Issue by slindstr** [clean-css/clean-css#573]
Hi!

First off, I wanna say thanks for this; clean-css is really great!

I wanted to float an idea by you guys to get your thoughts on what it would take to implement an option that would move media queries to the end of the CSS to assist in media merging. 

Doing this would require CSS rulesets to be authored in an order from most general to most specific so they embrace the cascade and build off each other:
- normalizing styles
- general styles
  - headings
  - paragraphs
  - links
  - etc.
- reusable component classes
  - buttons
  - modals
  - dropdowns
  - etc.
- layouts or container classes that contain components
  - navbar
  - search results (grid)
  - search results (table)
  - etc.

Assuming that each of the sub-bullets is authored in a separate file and contains media queries relevant to only the code in that file, then in theory those media queries could:
1. be extracted from their files (or single file if they've already been concatenated)
2. tokenized by their media value and appended to a collection for the tokenized value in the order they appear
3. for each collection of media values:
   - merge all of the rulesets into one ruleset in the order they appear (looks like `AdvancedOptimizer.mergeMediaQueries` does this)
   - append the newly merged media queries to the end of the stylesheets

Since most CSS in the wild is written haphazardly, this option should default to being turned off. I could also see an option where the order of media queries can be specified rather than inferring it from the CSS.

If something like this can't be done, then I guess another solution would be to just author media queries in separate files, order them appropriately, and concatenate and minify them. This is kind of a bummer, though, because you lose the context of what's being styled differently in those media queries since they're separate.

This might be a pipe dream, but I wanted to get your thoughts. 

Thanks!

**Comment by jakubpawlowicz** [comment]
@slindstr I'm glad you like clean-css and thanks for sharing your idea! It's not in fact a pipe dream as in a scenario where CSS is truly semantic it should be possible to do what you described. The way people write SASS these days result in lots of media blocks being repeated so it's a burning issue.

In fact if you take a look at https://github.com/jakubpawlowicz/clean-css/tree/semantic-merging branch then you'll find some of the preliminary work on making it possible. The algorithm is pretty stupid so far but there's more coming and the first version will definitely land in the upcoming version 3.3 behind `--semanting-merging` flag.

**Comment by slindstr** [comment]
Cool! Let me know how I can help out with this enhancement and I'll see what I can do. Probably won't be able to work on it for the next couple of weeks though.

**Comment by jakubpawlowicz** [comment]
I think there's a long journey ahead to make it happen but we should do it in small steps. First one is having a basic semantic merging in 3.3.

Any testing and ideas would be more than welcome! I'll ping you once it goes out into the wild.

**Comment by jakubpawlowicz** [comment]
Won't fix as clean-css is going into [maintenance mode](https://github.com/clean-css/clean-css/discussions/1209).
