### ISSUE TITLE
Smarter media query merging for 'mobile-first' technique

### ISSUE THREAD

**Issue by simeyla** [clean-css/clean-css#913]
Love to see some of the smart merging that is being done. One feature which seems to have not been implemented is the removal of redundant selectors when using 'mobile-first' techniques.

With this techniques you write selectors for the default values and then create new media queries for wider devices. The way I have used mixins has resulted in A LOT of redundant code.

It seems that for something like a 'min-width', that if a selector has already been defined for a smaller width that it can be ignored as redundant. (of course provided it wasn't redefined in between)

I can't think of anything that would improve my CSS compression more than this feature but have no time to look into it myself. Is this something that will ever be implemented? 

**Sample with notes:**

    h1
    {
        @media (min-width: 20em) 
        {

            color: red;     // this is already removed by today's optimizer (awesome!) 
            display: block;
        };

        @media (min-width: 20em) 
        {

            color: orange;
            display: block;
        };
    }

    h2
    {
         color: yellow;     

         @media (min-width: 20em) 
         {
             color: yellow;      // this should be ignored because it is redundant and already defined
             display: block;
         };

         @media (min-width: 40em) 
         {
             color: green;
             display: block;     // this should be ignored because it is defined for a 'smaller' width
         };
    }

**Comment by jakubpawlowicz** [comment]
Thanks @simeyla, interesting ideas! I'm marking it as an enhancement for future consideration.

**Comment by simeyla** [comment]
@jakubpawlowicz ever thought anymore about this? would love to know how much it would shrink my code by

**Comment by jakubpawlowicz** [comment]
Unfortunately I didn't have a chance to do so yet..

**Comment by jakubpawlowicz** [comment]
Won't fix as clean-css is going into [maintenance mode](https://github.com/clean-css/clean-css/discussions/1209).
