### ISSUE TITLE
O0 is not equivalent to O1 all:off

### ISSUE THREAD

**Issue by ivanreese** [clean-css/clean-css#954]
### Environment

* clean-css version - `npm ls clean-css`: 4.1.5
* node.js version - `node -v`: 8.1.0
* operating system: macOS 10.12.5

### Configuration options

-O0
```bash
cleancss public/styles.css -o public/clean.css -O0
```

-O1 all:off
```bash
cleancss public/styles.css -o public/clean.css -O1 all:off
```

### Input CSS

```css
* {
  min-width: 0%;
}
```

### Actual output CSS

-O0
```css
*{min-width:0%}
```

-O1 all:off
```css
*{min-width:0}
```

Note that the `%` unit has been removed.

### Expected output CSS

```css
*{min-width:0%}
```

Why does this matter? Because, due to flexbox bugs in IE11, `min-width: 0` is interpreted as `min-width: 0px`, which is not evaluated the same way as `min-width: 0%` (even though they are, to the best of my knowledge, equivalent according to the spec). I have a repro where `0px` causes a layout glitch in IE11, and `0%` does not! You can use the IE11 web dev tools to change the unit back and forth between `0px` and `0%` and see things break and unbreak. Maddening, hey?

What's doubly painful for me is.. I can't find which clean-css configuration option is causing the `%` unit to be stripped. I'd like to turn that config option off, but it doesn't seem to be documented, and I haven't be able to find it by doing a brief source dive. If I can't turn this unit stripping off, I'm afraid I'll be stuck using O0 to compile my projects, which basically defeats the purpose of using clean-css at all.

So, two things I'd love:

1. I'd love `-O1 all:off` to be equivalent to `-O0`, or alternatively for the difference to be documented.
2. I'd love to know why unit are being stripped when run with `-O1 all:off`, and what config option I can set to stop units from being stripped.

Cheers!

**Comment by jakubpawlowicz** [comment]
Hey @ivanreese, thanks a lot for a lot of feedback!

The thing is some level 1 optimizations are not controlled by optimization level but compatibility settings, see https://github.com/jakubpawlowicz/clean-css/blob/master/lib/optimizer/level-1/optimize.js#L458

I think we should fix it to make `-O1 all:off` behave as `-O0` by allowing level 1 options to control it too. I don't think those should be moved to optimization levels as those options handle incompatibilities between browsers. What do you think?

In the meantime you can just use `-O1 all:off -c -properties.zeroUnits`.

**Comment by ivanreese** [comment]
The tip that this is related to compatibility is exactly what I needed to know, and your suggested workaround means I should be able to resolve my IE11 flexbox issue by disabling that compatibility setting. I'll try it out next week, and let you know if I hit any other issues.

If it were up to me, I'd add compatibility modes for IE11+ and Edge+, and have `zeroUnits` turned off for all except Edge+ (since, in my testing, Edge isn't affected by this bug — but I only tested a recent version of Edge). But I'm not familiar with the design goals behind the compatibility modes feature, and what criteria must be satisfied for an optimization to be considered unsafe for a particular browser. You should do whatever best fits the norms of the project.

It'd also be nice for there to be a note under the [Optimization Levels](https://github.com/jakubpawlowicz/clean-css#optimization-levels) section of the docs explaining that some optimizations are controlled by compatibility settings. Because right now, under both Level 1 and Level 2, it says "Here is a full list of available options", which is a bit misleading if you aren't aware of how the compatibility modes feature works. In my reading of the docs, I thought that the compatibility settings were just about adding or removing IE-specific hacks.

Looking over the docs further, I find it odd that there's both a Level 1 `replaceZeroUnits ` and a compatibility setting `zeroUnits`. It looks like they do the same thing? How am I supposed to know whether they're the same or different, or whether one setting overrides the other setting? So yeah.. clearer documentation about the relationship between optimization levels and compatibility settings would be great.

**Comment by ivanreese** [comment]
Also, it looks like `zeroUnits` isn't adjusted by any of the compatibility modes (according to [this](https://github.com/jakubpawlowicz/clean-css/blob/master/lib/options/compatibility.js)). Perhaps it shouldn't be a compatibility setting at all?

**Comment by jakubpawlowicz** [comment]
Given there are restrictions [when units are removed](https://github.com/jakubpawlowicz/clean-css/blob/master/lib/optimizer/level-1/optimize.js#L266-L276) you are probably right!

**Comment by jakubpawlowicz** [comment]
This issue has been long overdue, but in clean-css 5.x 1) the level 1 optimizations are applied on a much more fine-grained level, see https://github.com/clean-css/clean-css/blob/master/lib/optimizer/configuration.js#L1172, and 2) `zeroUnits` compatibility flag is always respected, see https://github.com/clean-css/clean-css/blob/master/lib/optimizer/level-1/value-optimizers/zero.js#L36

One can run now this and they will be fine:

```js
var CleanCSS = require('clean-css');
new CleanCSS({compatibility: {properties: {zeroUnits: false}}, level: {1: {all: false}}}).minify('*{min-width:0%}')
```

Hope it still helps someone.
