### ISSUE TITLE
RegExp support for specialComments

### ISSUE THREAD

**Issue by silverwind** [clean-css/clean-css#963]
I think it would be useful to be able to define how a special comment looks like so we can match things like userstyle placeholders like `/*[[base-color]]*/`.

`uglifyjs` has a `comments` option that works pretty similar, thought they don't count comments:

> comments (default false) -- pass true or "all" to preserve all comments, "some" to preserve some comments, a regular expression string (e.g. /^!/) or a function.

Because clean-css counts comments, I think a RegExp could not be added to the existing option without losing the counting functionality. Maybe add a new `specialCommentsRe` option to define a RegExp, defaulting to `^!`.

**Comment by jakubpawlowicz** [comment]
Interesting idea @silverwind, would help solving an outstanding issue with placeholders #369.

**Comment by silverwind** [comment]
@jakubpawlowicz I think it's not enough to solve that. We'd need to regard special comments as valid CSS values, otherwise the declaration will get dropped:

````console
$ echo 'div {color: /*!white*/}' | cleancss -O1 'specialComments:all'
WARNING: Empty property 'color' at 1:5. Ignoring.
div{/*!white*/}%
````
Probably best done via a separate option as it is actually invalid CSS.

**Comment by jakubpawlowicz** [comment]
👍 it's not that simple!

**Comment by jakubpawlowicz** [comment]
Won't fix as clean-css is going into [maintenance mode](https://github.com/clean-css/clean-css/discussions/1209).
