### ISSUE TITLE
`source-map-inline-sources` uses Windows paths on Windows

### ISSUE THREAD

**Issue by XhmikosR** [clean-css/clean-css#964]
I was running `npm run dist` on Bootstrap v4-dev branch and I notice that the map files have the paths with Windows separator. I don't think that's right.

```
{"version":3,"sources":["../../scss/bootstrap.scss","../../scss/_print.scss","dist/css/bootstrap.css","../../scss/_reboot.scss"
```

vs this on Windows

```
{"version":3,"sources":["..\\..\\scss\\bootstrap.scss","..\\..\\scss\\_print.scss","dist\\css\\bootstrap.css","..\\..\\scss\\_reboot.scss"
```

/CC @jakubpawlowicz 

Using v4.1.7.

**Comment by XhmikosR** [comment]
OK, this might not be an issue, but is it really needed to use Windows separator?

**Comment by jakubpawlowicz** [comment]
You built it on Windows, right? I wonder how such source map is interpreted by a non-Windows browser, e.g. Chrome on Mac.

**Comment by XhmikosR** [comment]
Yeah.

That is why I think always using the nix separator is better.

**Comment by jakubpawlowicz** [comment]
I think we already force UNIX path separator to URLs.

**Comment by XhmikosR** [comment]
Then it would make sense to do the same here too? I don't seem to have any issues with the unix separator on Windows for sourcemaps.

**Comment by jakubpawlowicz** [comment]
Worth making it simpler. Scheduling for 4.2.

**Comment by XhmikosR** [comment]
@jakubpawlowicz: so any news about this? It makes collaboration with people on different OS'es than I am hard and messy. :/

**Comment by jakubpawlowicz** [comment]
For backwards compatibility I'd rather add it as an option defaulting to sth like `{ lineBreak: 'system' }` where user can override it with `'unix'`, `'windows'`, or `'lf'`, `'crlf'`, also see https://github.com/jakubpawlowicz/clean-css/issues/238

**Comment by XhmikosR** [comment]
I don't think the current behavior is right but I haven't read the spec. If the specs allow Windows paths then what you suggest makes sense, otherwise this should be considered a bug and just fixed.

#238 makes sense, totally. Usually I don't hit this because I try to set LF on the repo side plus the CSS are usually one line so no line ending :P

**Comment by XhmikosR** [comment]
@jakubpawlowicz: can you please take care of this? I'm pretty sure the current behavior is non-standard even if it works.

**Comment by jakubpawlowicz** [comment]
Sure, we can have a switch in 4.2 as described above. Then default it to `unix` from v5. Does it sound right?

**Comment by XhmikosR** [comment]
Sounds good, although, I don't see why one would even need the paths to be Windows-like, when clearly, using unix works everywhere...

**Comment by jakubpawlowicz** [comment]
Me neither but I work with *nix systems only so can't tell if there's a use case for CRLF.

**Comment by XhmikosR** [comment]
I use Windows machines, and I see no use case for this. Browsers work just fine with unix separators.

**Comment by XhmikosR** [comment]
I mean, it's like with URLs; both might work, but what do we use?

I can't find anything in the specs so I guess this should be handled like URLs.

Thus, this isn't a feature request, rather a bug report and no feature should be added; the original behavior should be changed to use unix paths.

**Comment by XhmikosR** [comment]
@jakubpawlowicz: any news?

**Comment by mvelosop** [comment]
Hi @jakubpawlowicz, just to add one more upvote to this!

And I've also found that on Windows the minification adds a CRLF in the packed line:
![image](https://user-images.githubusercontent.com/7357806/38496354-295ef1a2-3bf5-11e8-99e1-3fb1ee423a87.png)
but the comment lines are ok:
![image](https://user-images.githubusercontent.com/7357806/38496474-96301fa4-3bf5-11e8-8481-55de7cbff0ad.png)

**Comment by XhmikosR** [comment]
@jakubpawlowicz: ping

**Comment by jakubpawlowicz** [comment]
Fixed in master, in 4.2.0 soon.

**Comment by XhmikosR** [comment]
Awesome, thanks @jakubpawlowicz !

**Comment by jakubpawlowicz** [comment]
4.2.0 is out - have a look at `breakWith` in https://github.com/jakubpawlowicz/clean-css#formatting-options

**Comment by XhmikosR** [comment]
@jakubpawlowicz: this issue was about the path separator though. Is this addressed in 4.2.0 too?

How can I specify the format option to enforce `\n` via the CLI?

Thanks!

**Comment by jakubpawlowicz** [comment]
Ooops, I somehow focused on the `breaksWith`. Will add an option to configure that too.

Re CLI you can use `cleancss --format breaksWith=lf` or `cleancss --format breaksWith=unix`. Just added it to CLI readme.

**Comment by XhmikosR** [comment]
Thanks for the help!

Yeah, the path separator is still an issue with 4.2.0.

**Comment by jakubpawlowicz** [comment]
Do you use CLI or some sort of 3rd party library on top of clean-css?

**Comment by XhmikosR** [comment]
@jakubpawlowicz: nope. https://github.com/twbs/bootstrap/blob/v4-dev/package.json#L36

**Comment by jakubpawlowicz** [comment]
It's in our CLI so it has to be fixed there - that's the line: https://github.com/jakubpawlowicz/clean-css-cli/blob/master/index.js#L249

**Comment by XhmikosR** [comment]
Yeah, but I'm still seeing one CRLF line just before the `sourceMappingURL` locally on Windows if I just do `npm run css-minify`

**Comment by XhmikosR** [comment]
@jakubpawlowicz: yeah that line is wrong. It shouldn't be OS dependent. It should take into consideration the `breaksWith` option.

**Comment by jakubpawlowicz** [comment]
^ is fixed in CLI 4.2.1

**Comment by XhmikosR** [comment]
@jakubpawlowicz: definitely not fixed.

**Comment by XhmikosR** [comment]
I made an issue in the CLI repo about the line endings issue https://github.com/jakubpawlowicz/clean-css-cli/issues/26

**Comment by XhmikosR** [comment]
@Johann-S: any chance you could have a look? It doesn't seem there's enough interest to fix this and it definitely affects us.

**Comment by seowalex** [comment]
Would love some news on this as well.

**Comment by XhmikosR** [comment]
@jakubpawlowicz so about this is issue, which is still present on master. I believe you should always use Linux path separators in sourcemaps. If this issue is solved, then only the linebreak issue is left to fix (https://github.com/jakubpawlowicz/clean-css-cli/issues/26 but probably here too) and we should be able to get reproducible builds regardless of OS.

**Comment by jakubpawlowicz** [comment]
Won't fix as clean-css is going into [maintenance mode](https://github.com/clean-css/clean-css/discussions/1209).

**Comment by XhmikosR** [comment]
That's a pity because this is a real bug.

**Comment by jakubpawlowicz** [comment]
PRs are welcomed!
