### ISSUE TITLE
media queries throw errors if first in file

### ISSUE THREAD

**Issue by jukkamaljanen** [clean-css/clean-css#968]
A css file that starts with:
```
@media (min-width: 768px)
{
    #content
    {
        width: 750px;
    }
}
```

Will throw something like:
> Unexpected '}' at Assets/css/module.css:7:0.,Invalid property name '#content
>     {
>         width' at Assets/css/module.css:3:4. Ignoring.,Invalid selector '}
> 
> #content' at Assets/css/module.css:7:0. Ignoring.

If the file starts with any _normal_ rule, it works fine. Newest versio up to date. Bug seems to appear since 4.0

I'm using:
- Visual Studio 2015 on W10
- .NET 4.6.2 C# Class Library project
- Grunt 0.4.5 and 1.0.1
- grunt-contrib-cssmin 2.2.1 (their readme directs issues to here)
- Css-files in question are embedded resources in project.
- Example solution in attachment (open --> restore packages -> run cssmin task). [TestiSolution.zip](https://github.com/jakubpawlowicz/clean-css/files/1273758/TestiSolution.zip)

**Comment by jakubpawlowicz** [comment]
Sorry @jukkamaljanen for not replying earlier. I tested the snippet you provided and I get the right output. Could you please give me some more details as described in https://github.com/jakubpawlowicz/clean-css/blob/master/CONTRIBUTING.md?

**Comment by jukkamaljanen** [comment]
Hi, thank you for reply. I updated the first post with more information. The TestiSolution.zip contains a minimal VS solution that triggers the error for me. I hope this helps to reproduce the issue.

**Comment by User00015** [comment]
Three years later, and I just ran into this bug.

I'm using:
VS2019 16.6.2
.NET 4.8
Grunt 1.3.0
cssmin 3.0.0

css file is not being generated or pre-compiled by SASS/SCSS, it is being combined as part of the gruntfile work.

My css file contains @media print { ... } and throws this exact error. Putting a completely bogus css class above this line fixed the error as suggested by the bug report. Big thanks to original reporter for discovering the work-around to this annoying bug.

**Comment by jakubpawlowicz** [comment]
Won't fix as clean-css is going into [maintenance mode](https://github.com/clean-css/clean-css/discussions/1209).
