### ISSUE TITLE
Make optional removing comments

### ISSUE THREAD

**Issue by valsaven** [clean-css/clean-css#991]
It could be useful for sites like https://userstyles.org/ where its templates should be like this `/*[[template]]*/`
It won't work if you just add `!` after an asterisk (like in a special comment).

**Comment by jakubpawlowicz** [comment]
I think we can handle them in an intelligent way, see #369 and #963.

**Comment by Dakshank** [comment]
waiting for the update

**Comment by jakubpawlowicz** [comment]
Won't fix as clean-css is going into [maintenance mode](https://github.com/clean-css/clean-css/discussions/1209).
