### ISSUE TITLE
Import statements are not processed due to BOMs at the beginning of the file

### ISSUE THREAD

**Issue by FourSpotProject** [clean-css/clean-css#999]
### Environment

* clean-css version - `npm ls clean-css`: 4.1.9
* node.js version - `node -v`: 9.4.0
* operating system: windows 10

When I started to use the command line version of clean-css, it wasn't able to process the import statements of my css and gave me following warning message:

```
"Invalid selector '@import url("./plugin/flexslider.css");
@import url("./plugin/owl.carousel.css");
@import url("./plugin/mediaelementplayer.css");
@import url("./plugin/colorbox.css");
@import url("./plugin/jquery.fs.tipper.css");
@import url(https://fonts.googleapis.com/css?family=Raleway:400,100,200,300,500,600,700,800,900);








::-moz-selection' at 1:0. Ignoring."
```

I created a node-script in order to use the api-version of clean-css and debugged my way through it. Turned out that (at least on my system), the first bytes parsed by the tokenizer are 0xFEFF, i.e. the BOM for UTF-16, which in turn doesn't work with the conditional statement in line 186 in tokenize.js as it requires the first character to be the '@'.
My fix was to add a trim statement before handing over the css to the library and maybe this behavior could be included into clean-css to make it more robust.

**Comment by jakubpawlowicz** [comment]
Hey @FourSpotProject - would you be able to attach a sample file or mail it to me (see package.json for email)?

**Comment by jakubpawlowicz** [comment]
Won't fix as clean-css is going into [maintenance mode](https://github.com/clean-css/clean-css/discussions/1209).
